FROM bellsoft/liberica-openjdk-alpine
RUN apk add curl jq
WORKDIR D:/eclipseWorkspace/DesignDemo
COPY target/selenium-docker.jar selenium-docker.jar
COPY target/selenium-docker-tests.jar selenium-docker-tests.jar
COPY target/libs libs
COPY testng.xml testng.xml
ENTRYPOINT java -cp selenium-docker.jar:selenium-docker-tests.jar:libs/* -DHUB_HOST=$HUB_HOST org.testng.TestNG $MODULE
#Add healthcheck.sh healthcheck.sh
#ENTRYPOINT sh healthcheck.sh